name: Create Release for Specific Folder

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: true
      folder_path:
        description: 'Relative path to the folder to release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip the folder
        run: |
          zip -r folder.zip ${{ github.event.inputs.folder_path }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: "Release for ${{ github.event.inputs.folder_path }}"
          files: folder.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
