/*==========================================================================================*/
/*======================================== Tâche 1 =========================================*/
/*==========================================================================================*/
/*========================================= Tables =========================================*/

DROP TABLE ADRESSE_PERSONNE CASCADE CONSTRAINTS;
DROP TABLE ADRESSE CASCADE CONSTRAINTS;
DROP TABLE PERSONNE CASCADE CONSTRAINTS;
DROP TABLE DEPARTEMENT CASCADE CONSTRAINTS;
DROP TABLE ETUDIANT CASCADE CONSTRAINTS;
DROP TABLE SESSION_ CASCADE CONSTRAINTS;
DROP TABLE PREALABLE CASCADE CONSTRAINTS;
DROP TABLE COURS CASCADE CONSTRAINTS;
DROP TABLE STATUT_ENSEIGNANT CASCADE CONSTRAINTS;
DROP TABLE LOCAL CASCADE CONSTRAINTS;
DROP TABLE ENSEIGNANT CASCADE CONSTRAINTS;
DROP TABLE PERIODE CASCADE CONSTRAINTS;
DROP TABLE PERIODE_COURS_ENSEIGNE CASCADE CONSTRAINTS;
DROP TABLE STATUT_ETUDIANT_COURS_ENSEIGNE CASCADE CONSTRAINTS;
DROP TABLE ETUDIANT_COURS_ENSEIGNE CASCADE CONSTRAINTS;
DROP TABLE COURS_ENSEIGNE CASCADE CONSTRAINTS;
DROP TABLE STATUT_ETUDIANT CASCADE CONSTRAINTS;
BEGIN
    FOR rec IN (SELECT object_name FROM user_objects WHERE object_type = 'PROCEDURE') LOOP
        EXECUTE IMMEDIATE 'DROP PROCEDURE ' || rec.object_name;
    END LOOP;
	FOR rec IN (SELECT view_name FROM user_views) LOOP
        EXECUTE IMMEDIATE 'DROP VIEW ' || rec.view_name;
    END LOOP;
END;
/


/*=============================================*/
/*================== ADRESSE ==================*/
CREATE TABLE ADRESSE
(
    ID_ADRESSE     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITRE          VARCHAR2(50),
    ADRESSE_CIVILE VARCHAR2(50) NOT NULL,
    VILLE          VARCHAR2(50) NOT NULL,
    CODE_POSTAL    VARCHAR2(10) NOT NULL,
    PAYS           VARCHAR2(50) NOT NULL
);

/*=============================================*/
/*================== PERSONNE =================*/
CREATE TABLE PERSONNE
(
    ID_PERSONNE        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOM                VARCHAR2(50)    NOT NULL,
    PRENOM             VARCHAR2(50)    NOT NULL,
    NAS                NCHAR(9) UNIQUE NOT NULL,
    DATE_NAISSANCE     DATE            NOT NULL,
    COURRIEL_PERSONNEL VARCHAR2(100)   NOT NULL,
    NUMERO_TELEPHONE   VARCHAR2(11)    NOT NULL,
    CONSTRAINT CHECK_NAS_FORMAT CHECK (REGEXP_LIKE(NAS, '^[0-9]{9}$')),
    CONSTRAINT CHECK_COURRIEL_PERSONNEL_FORMAT CHECK (REGEXP_LIKE(COURRIEL_PERSONNEL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CONSTRAINT CHECK_NUMERO_TELEPHONE_FORMAT CHECK (REGEXP_LIKE(NUMERO_TELEPHONE, '^[0-9]{10,11}$'))
);

/*=============================================*/
/*============= ADRESSE_PERSONNE ==============*/
CREATE TABLE ADRESSE_PERSONNE
(
    ID_ADRESSE_PERSONNE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_PERSONNE         NUMBER(*, 0) NOT NULL,
    ID_ADRESSE          NUMBER(*, 0) NOT NULL,
    FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE,
    FOREIGN KEY (ID_ADRESSE) REFERENCES ADRESSE
);

/*=============================================*/
/*================ DEPARTEMENT ================*/
CREATE TABLE DEPARTEMENT
(
    ID_DEPARTEMENT     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOM                VARCHAR2(50)        NOT NULL,
    ID_DIRECTEUR       NUMBER(*, 0), /*Contrainte "Ajout sans directeur" du TP1*/
    NUMERO_DEPARTEMENT NUMBER(*, 0) UNIQUE NOT NULL
);

/*=============================================*/
/*================== LOCAL ====================*/
CREATE TABLE LOCAL
(
    CODE        NCHAR(7) PRIMARY KEY,
    DESCRIPTION VARCHAR(50),
    CONSTRAINT CHECK_CODE_FORMAT CHECK (REGEXP_LIKE(CODE, '^[A-G][0-9]-[1-4][0-9]{3}$'))
);

/*=============================================*/
/*================ ENSEIGNANT =================*/
CREATE TABLE STATUT_ENSEIGNANT
(
    CODE        NUMBER(2, 0) PRIMARY KEY,
    DESCRIPTION VARCHAR2(100)
);

INSERT INTO STATUT_ENSEIGNANT (CODE, DESCRIPTION)
VALUES (0, 'Non actif (a quitté)');
INSERT INTO STATUT_ENSEIGNANT (CODE, DESCRIPTION)
VALUES (1, 'Enseignant stagiaire');
INSERT INTO STATUT_ENSEIGNANT (CODE, DESCRIPTION)
VALUES (2, 'Enseignant titulaire');
INSERT INTO STATUT_ENSEIGNANT (CODE, DESCRIPTION)
VALUES (3, 'Enseignant contractuel');
INSERT INTO STATUT_ENSEIGNANT (CODE, DESCRIPTION)
VALUES (4, 'Enseignant responsable de département');


CREATE TABLE ENSEIGNANT
(
    ID_ENSEIGNANT          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_DEPARTEMENT         NUMBER(*, 0)         NOT NULL,
    ID_PERSONNE            NUMBER(*, 0)         NOT NULL,
    CODE_LOCAL             NCHAR(7),
    CODE_STATUT            NUMBER(2, 0)         NOT NULL,
    DATE_EMBAUCHE          DATE DEFAULT SYSDATE,
    COURRIEL_PROFESSIONNEL VARCHAR2(100) UNIQUE NOT NULL,
    NUMERO_LIGNE_DIRECT    VARCHAR2(11) UNIQUE  NOT NULL,
    POSTE_TELEPHONE        NUMBER(4, 0) UNIQUE  NOT NULL,
    FOREIGN KEY (ID_DEPARTEMENT) REFERENCES DEPARTEMENT,
    FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE,
    FOREIGN KEY (CODE_LOCAL) REFERENCES LOCAL (CODE),
    FOREIGN KEY (CODE_STATUT) REFERENCES STATUT_ENSEIGNANT (CODE),
    CONSTRAINT CHECK_POSTE_TELEPHONE_FORMAT CHECK (REGEXP_LIKE(POSTE_TELEPHONE, '^[0-9]{4}$'))
);

/*=============================================*/
/*======== DEPARTEMENT - MODIFICATION =========*/
ALTER TABLE DEPARTEMENT
    ADD CONSTRAINT FK_DIRECTEUR FOREIGN KEY (ID_DIRECTEUR) REFERENCES ENSEIGNANT (ID_ENSEIGNANT);

/*=============================================*/
/*================= ETUDIANT ==================*/
CREATE TABLE STATUT_ETUDIANT
(
    CODE        NCHAR(1) PRIMARY KEY,
    DESCRIPTION VARCHAR2(100)
);

INSERT INTO STATUT_ETUDIANT (CODE, DESCRIPTION)
VALUES (N'C', 'Études en cours');
INSERT INTO STATUT_ETUDIANT (CODE, DESCRIPTION)
VALUES (N'A', 'Abandon du programme');
INSERT INTO STATUT_ETUDIANT (CODE, DESCRIPTION)
VALUES (N'T', 'Études terminées avec succès');
INSERT INTO STATUT_ETUDIANT (CODE, DESCRIPTION)
VALUES (N'S', 'Suspendu');
INSERT INTO STATUT_ETUDIANT (CODE, DESCRIPTION)
VALUES (N'P', 'Pause temporaire autorisée');


CREATE TABLE ETUDIANT
(
    ID_ETUDIANT       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_DEPARTEMENT    NUMBER               NOT NULL,
    ID_PERSONNE       NUMBER               NOT NULL,
    CODE_STATUT       NCHAR(1)             NOT NULL,
    CODE_PERMANENT    NCHAR(12) UNIQUE     NOT NULL,
    COURRIEL_SCOLAIRE VARCHAR2(100) UNIQUE NOT NULL,
    DATE_INSCRIPTION  DATE DEFAULT SYSDATE,
    FOREIGN KEY (ID_DEPARTEMENT) REFERENCES DEPARTEMENT (ID_DEPARTEMENT),
    FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE),
    FOREIGN KEY (CODE_STATUT) REFERENCES STATUT_ETUDIANT (CODE)
);

/*=============================================*/
/*=================== COURS ===================*/
CREATE TABLE COURS
(
    ID_COURS                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_ENSEIGNANT            NUMBER,
    ID_DEPARTEMENT           NUMBER              NOT NULL,
    TITRE                    VARCHAR2(50)        NOT NULL,
    SIGLE                    VARCHAR2(50) UNIQUE NOT NULL,
    DESCRIPTION              VARCHAR2(50),
    LIEN_SITE_WEB            VARCHAR2(50),
    CREDIT                   NUMBER(*, 0)        NOT NULL,
    NOMBRE_HEURE_COURS       NUMBER(*, 2)        NOT NULL,
    NOMBRE_HEURE_LABORATOIRE NUMBER(*, 2)        NOT NULL,
    NOMBRE_HEURE_TRAVAIL     NUMBER(*, 2)        NOT NULL,
    FOREIGN KEY (ID_ENSEIGNANT) REFERENCES ENSEIGNANT (ID_ENSEIGNANT),
    FOREIGN KEY (ID_DEPARTEMENT) REFERENCES DEPARTEMENT (ID_DEPARTEMENT),
    CONSTRAINT CHECK_SIGLE_FORMAT CHECK (REGEXP_LIKE(SIGLE, '^[0-9]{1,2}[A-Z]{3}[0-9]{3}$'))
);

CREATE TABLE PREALABLE
(
    ID_PREALABLE       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_COURS           NUMBER NOT NULL,
    ID_COURS_PREALABLE NUMBER NOT NULL,
    FOREIGN KEY (ID_COURS) REFERENCES COURS (ID_COURS),
    FOREIGN KEY (ID_COURS_PREALABLE) REFERENCES COURS (ID_COURS)
);

CREATE TABLE SESSION_
(
    ID_SESSION_ NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SESSION_    NUMBER(5, 0) UNIQUE,
    CONSTRAINT CHECK_SESSION_FORMAT CHECK (REGEXP_LIKE(SESSION_, '^[0-9]{4}[1-3]$'))
);

CREATE TABLE COURS_ENSEIGNE
(
    ID_COURS_ENSEIGNE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_ENSEIGNANT     NUMBER   NOT NULL,
    ID_SESSION_       NUMBER   NOT NULL,
    ID_COURS          NUMBER   NOT NULL,
    CODE_LOCAL        NCHAR(7) NOT NULL,
    FOREIGN KEY (ID_ENSEIGNANT) REFERENCES ENSEIGNANT (ID_ENSEIGNANT),
    FOREIGN KEY (ID_SESSION_) REFERENCES SESSION_ (ID_SESSION_),
    FOREIGN KEY (ID_COURS) REFERENCES COURS (ID_COURS),
    FOREIGN KEY (CODE_LOCAL) REFERENCES LOCAL (CODE)
);

/*=============================================*/
/*========== ETUDIANT_COURS_ENSEIGNE ==========*/
CREATE TABLE STATUT_ETUDIANT_COURS_ENSEIGNE
(
    CODE        VARCHAR2(2) PRIMARY KEY,
    DESCRIPTION VARCHAR2(100)
);

INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('A+', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('A', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('A-', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('B+', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('B', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('B-', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('C+', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('C', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('C-', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('D+', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('D', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('D-', 'Succès avec cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('S', 'Succès sans cote');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('E', 'Échec');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('I', 'Incomplet temporaire');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('X', 'Période d’inscription en cours');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('Y', 'Présentement en cours');
INSERT INTO STATUT_ETUDIANT_COURS_ENSEIGNE (CODE, DESCRIPTION)
VALUES ('Z', 'Cours annulé');


CREATE TABLE ETUDIANT_COURS_ENSEIGNE
(
    ID_ETUDIANT_COURS_ENSEIGNE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_ETUDIANT                NUMBER      NOT NULL,
    ID_COURS_ENSEIGNE          NUMBER      NOT NULL,
    CODE_STATUT                VARCHAR2(2) NOT NULL,
    NOTE_TOTALE                NUMBER(5, 2),
    CONSTRAINT CHECK_STATUT_NOTE CHECK (
        (CODE_STATUT IN ('A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'S', 'E') AND NOTE_TOTALE IS NOT NULL) OR
        (CODE_STATUT NOT IN ('A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'S', 'E') AND NOTE_TOTALE IS NULL)
    ),
    CONSTRAINT CHECK_NOTE_TOTAL CHECK (NOTE_TOTALE BETWEEN 0 AND 100),
    FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANT (ID_ETUDIANT),
    FOREIGN KEY (ID_COURS_ENSEIGNE) REFERENCES COURS_ENSEIGNE (ID_COURS_ENSEIGNE),
    FOREIGN KEY (CODE_STATUT) REFERENCES STATUT_ETUDIANT_COURS_ENSEIGNE (CODE)
);

/*=============================================*/
/*================== PERIODE ==================*/
CREATE TABLE PERIODE
(
    ID_PERIODE          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JOUR_SEMAINE        VARCHAR2(10) NOT NULL,
    HEURE_DEBUT_PERIODE NUMBER(2, 2) NOT NULL,
    TYPE_ACTIVITE       VARCHAR(30)  NOT NULL,
    CONSTRAINT CHECK_JOUR_SEMAINE CHECK (JOUR_SEMAINE IN ('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi')),
    CONSTRAINT CHECK_TYPE_ACTIVITE CHECK (TYPE_ACTIVITE IN ('Laboratoire', 'Travaux pratiques', 'Présentations', 'Immersion en entreprise', 'Autre'))
);

CREATE TABLE PERIODE_COURS_ENSEIGNE
(
    ID_PERIODE_COURS_ENSEIGNE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_COURS_ENSEIGNE         NUMBER NOT NULL,
    ID_PERIODE                NUMBER NOT NULL,
    FOREIGN KEY (ID_COURS_ENSEIGNE) REFERENCES COURS_ENSEIGNE (ID_COURS_ENSEIGNE),
    FOREIGN KEY (ID_PERIODE) REFERENCES PERIODE (ID_PERIODE)
);

/*==========================================================================================*/
/*======================================= Tâche 1.5 ========================================*/
/*==========================================================================================*/
/*====================================== Déclencheurs ======================================*/

CREATE OR REPLACE TRIGGER TRIGGER_VERIFIER_DIRECTEUR_EST_DANS_DEPARTEMENT
    BEFORE INSERT OR UPDATE
    ON DEPARTEMENT
    FOR EACH ROW
DECLARE
    v_id_departement_enseignant NUMBER;
BEGIN
    IF :NEW.ID_DIRECTEUR IS NOT NULL THEN
        -- Récupérer l'ID du département de l'enseignant
        SELECT ID_DEPARTEMENT
        INTO v_id_departement_enseignant
        FROM ENSEIGNANT
        WHERE ID_ENSEIGNANT = :NEW.ID_DIRECTEUR;

        -- Vérifier que l'enseignant est dans le même département que le département mis à jour
        IF v_id_departement_enseignant != :NEW.ID_DEPARTEMENT THEN
            RAISE_APPLICATION_ERROR(-20001, 'Le directeur doit être un enseignant dans le même département que celui-ci.');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRIGGER_VERIFIER_DIRECTEUR_EXISTE_DEPARTEMENT
    BEFORE INSERT OR UPDATE
    ON COURS
    FOR EACH ROW
DECLARE
    v_directeur NUMBER;
BEGIN
    -- Vérifie si le département associé au cours a un directeur
    SELECT ID_DIRECTEUR
    INTO v_directeur
    FROM DEPARTEMENT
    WHERE ID_DEPARTEMENT = :NEW.ID_DEPARTEMENT;

    IF v_directeur IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'Le département doit avoir un directeur avant d''assigner un cours.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRIGGER_VERIFIER_MEME_DEPARTEMENT_COURS_ENSEIGNANT
    BEFORE INSERT OR UPDATE
    ON COURS
    FOR EACH ROW
DECLARE
    v_id_departement_enseignant NUMBER;
BEGIN
    -- Vérifier si ID_ENSEIGNANT est NULL
    IF :NEW.ID_ENSEIGNANT IS NOT NULL THEN
        -- Récupérer l'ID du département de l'enseignant
        SELECT ID_DEPARTEMENT
        INTO v_id_departement_enseignant
        FROM ENSEIGNANT
        WHERE ID_ENSEIGNANT = :NEW.ID_ENSEIGNANT;

        -- Vérifier que l'enseignant est dans le même département que le cours
        IF v_id_departement_enseignant != :NEW.ID_DEPARTEMENT THEN
            RAISE_APPLICATION_ERROR(-20001, 'L''enseignant doit être dans le même département que le cours.');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRIGGER_VERIFIER_MEME_DEPARTEMENT_COURS_ENSEIGNE_ENSEIGNANT
    BEFORE INSERT OR UPDATE
    ON COURS_ENSEIGNE
    FOR EACH ROW
DECLARE
    v_id_departement_enseignant NUMBER;
    v_id_departement_cours      NUMBER;
BEGIN
    -- Récupérer l'ID du département de l'enseignant
    SELECT ID_DEPARTEMENT
    INTO v_id_departement_enseignant
    FROM ENSEIGNANT
    WHERE ID_ENSEIGNANT = :NEW.ID_ENSEIGNANT;
    
    -- Récuperer l'ID du département auquel le cours appartient
    SELECT ID_DEPARTEMENT
    INTO v_id_departement_cours
    FROM COURS
    WHERE ID_COURS = :NEW.ID_COURS;
    
    -- Vérifier que l'enseignant est dans le même département que le cours
    IF v_id_departement_enseignant != v_id_departement_cours THEN
        RAISE_APPLICATION_ERROR(-20001, 'L''enseignant doit être dans le même département que le cours.');
    END IF;
END;
/

/*==========================================================================================*/
/*======================================== Tâche 2 =========================================*/
/*==========================================================================================*/
/*================================== Procédures stockées ===================================*/

-- Département :

-- a. Ajout (sans directeur). 
CREATE OR REPLACE PROCEDURE AJOUTER_DEPARTEMENT_SANS_DIRECTEUR(
    p_nom IN VARCHAR2,
    p_numero_departement IN NUMBER
)
    IS
BEGIN
    INSERT INTO DEPARTEMENT (NOM, NUMERO_DEPARTEMENT, ID_DIRECTEUR)
    VALUES (p_nom, p_numero_departement, NULL);

    COMMIT;
END;
/

-- b. Assignation d’un directeur.
CREATE OR REPLACE PROCEDURE ASSIGNER_DIRECTEUR_DEPARTEMENT(
    p_id_departement IN NUMBER,
    p_id_directeur IN NUMBER
)
    IS
    v_departement_count NUMBER;
BEGIN
    -- Vérifier si le département existe
    SELECT COUNT(*)
    INTO v_departement_count
    FROM DEPARTEMENT
    WHERE ID_DEPARTEMENT = p_id_departement;

    IF v_departement_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Le département spécifié n''existe pas.');
    END IF;

    -- Mise à jour du directeur dans le département
    UPDATE DEPARTEMENT
    SET ID_DIRECTEUR = p_id_directeur
    WHERE ID_DEPARTEMENT = p_id_departement;

    COMMIT;
END;
/

-- Cours :

-- a. Ajout cours. 
CREATE OR REPLACE PROCEDURE AJOUTER_COURS(
    p_id_enseignant IN NUMBER,
    p_id_departement IN NUMBER,
    p_titre IN VARCHAR2,
    p_sigle IN VARCHAR2,
    p_description IN VARCHAR2,
    p_lien_site_web IN VARCHAR2,
    p_credit IN NUMBER,
    p_nombre_heure_cours IN NUMBER,
    p_nombre_heure_laboratoire IN NUMBER,
    p_nombre_heure_travail IN NUMBER
)
    IS
BEGIN
    INSERT INTO COURS (ID_ENSEIGNANT,
                       ID_DEPARTEMENT,
                       TITRE,
                       SIGLE,
                       DESCRIPTION,
                       LIEN_SITE_WEB,
                       CREDIT,
                       NOMBRE_HEURE_COURS,
                       NOMBRE_HEURE_LABORATOIRE,
                       NOMBRE_HEURE_TRAVAIL)
    VALUES (p_id_enseignant,
            p_id_departement,
            p_titre,
            p_sigle,
            p_description,
            p_lien_site_web,
            p_credit,
            p_nombre_heure_cours,
            p_nombre_heure_laboratoire,
            p_nombre_heure_travail);

    COMMIT;
END;
/

-- b. Assignation de préalables. 
CREATE OR REPLACE PROCEDURE AJOUTER_PREALABLE(
    p_id_cours IN NUMBER,
    p_id_cours_prealable IN NUMBER
)
    IS
BEGIN
    -- Vérifier si le cours existe
    DECLARE
        v_cours_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_cours_count
        FROM COURS
        WHERE ID_COURS = p_id_cours;

        IF v_cours_count = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Le cours spécifié n''existe pas.');
        END IF;
    END;

    -- Vérifier si le cours préalable existe
    DECLARE
        v_prealable_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_prealable_count
        FROM COURS
        WHERE ID_COURS = p_id_cours_prealable;

        IF v_prealable_count = 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Le cours préalable spécifié n''existe pas.');
        END IF;
    END;

    -- Ajouter le préalable au cours
    INSERT INTO PREALABLE (ID_COURS,
                           ID_COURS_PREALABLE)
    VALUES (p_id_cours,
            p_id_cours_prealable);

    COMMIT;
END;
/

-- c. Modification cours. 
CREATE OR REPLACE PROCEDURE MODIFIER_COURS(
    p_id_cours IN NUMBER,
    p_id_enseignant IN NUMBER DEFAULT NULL,
    p_id_departement IN NUMBER DEFAULT NULL,
    p_titre IN VARCHAR2 DEFAULT NULL,
    p_sigle IN VARCHAR2 DEFAULT NULL,
    p_description IN VARCHAR2 DEFAULT NULL,
    p_lien_site_web IN VARCHAR2 DEFAULT NULL,
    p_credit IN NUMBER DEFAULT NULL,
    p_nombre_heure_cours IN NUMBER DEFAULT NULL,
    p_nombre_heure_laboratoire IN NUMBER DEFAULT NULL,
    p_nombre_heure_travail IN NUMBER DEFAULT NULL
)
    IS
BEGIN
    -- Mise à jour des informations du cours
    UPDATE COURS
    SET ID_ENSEIGNANT            = COALESCE(p_id_enseignant, ID_ENSEIGNANT),
        ID_DEPARTEMENT           = COALESCE(p_id_departement, ID_DEPARTEMENT),
        TITRE                    = COALESCE(p_titre, TITRE),
        SIGLE                    = COALESCE(p_sigle, SIGLE),
        DESCRIPTION              = COALESCE(p_description, DESCRIPTION),
        LIEN_SITE_WEB            = COALESCE(p_lien_site_web, LIEN_SITE_WEB),
        CREDIT                   = COALESCE(p_credit, CREDIT),
        NOMBRE_HEURE_COURS       = COALESCE(p_nombre_heure_cours, NOMBRE_HEURE_COURS),
        NOMBRE_HEURE_LABORATOIRE = COALESCE(p_nombre_heure_laboratoire, NOMBRE_HEURE_LABORATOIRE),
        NOMBRE_HEURE_TRAVAIL     = COALESCE(p_nombre_heure_travail, NOMBRE_HEURE_TRAVAIL)
    WHERE ID_COURS = p_id_cours;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Le cours spécifié n''existe pas.');
    END IF;

    COMMIT;
END;
/

-- d. Modification préalables
CREATE OR REPLACE PROCEDURE MODIFIER_PREALABLE(
    p_id_prealable IN NUMBER,
    p_id_cours IN NUMBER DEFAULT NULL,
    p_id_cours_prealable IN NUMBER DEFAULT NULL
)
    IS
BEGIN
    -- Mise à jour des informations du préalable
    UPDATE PREALABLE
    SET ID_COURS           = COALESCE(p_id_cours, ID_COURS),
        ID_COURS_PREALABLE = COALESCE(p_id_cours_prealable, ID_COURS_PREALABLE)
    WHERE ID_PREALABLE = p_id_prealable;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Le préalable spécifié n''existe pas.');
    END IF;

    COMMIT;
END;
/

-- Étudiant :

-- a. Ajout.
CREATE OR REPLACE PROCEDURE AJOUTER_ETUDIANT(
    new_nom VARCHAR2,
    new_prenom VARCHAR2,
    new_nas VARCHAR2,
    new_date_naissance VARCHAR2,
    new_courriel_personnel VARCHAR2,
    new_numero_telephone VARCHAR2,
    new_id_departement NUMBER,
    new_status_etudiant NCHAR) AS
BEGIN
    DECLARE
        -- Déclaration des variables
        id_personne                          NUMBER        := NULL;
        id_etudiant                          NUMBER        := NULL;
        courriel_scolaire                    VARCHAR2(100) := '';
        nombre_etudiant_avec_meme_personne   NUMBER        := 0;
        nombre_etudiant_avec_meme_nom_prenom NUMBER        := 0;
        code_permament                       VARCHAR2(12)  := '';
    BEGIN
        -- Vérifie si une personne existe déjà avec le NAS en entrée
        BEGIN
            SELECT ID_PERSONNE INTO id_personne FROM PERSONNE WHERE NAS = new_nas;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                id_personne := NULL;
        END;
        -- Si aucune personne n'a ce NAS, on crée une nouvelle personne
        IF id_personne IS NULL THEN
            INSERT INTO PERSONNE (NOM, PRENOM, NAS, DATE_NAISSANCE, COURRIEL_PERSONNEL, NUMERO_TELEPHONE)
            VALUES (new_nom, new_prenom, new_nas, TO_DATE(new_date_naissance, 'YYYY-MM-DD'), new_courriel_personnel,
                    new_numero_telephone)
            RETURNING ID_PERSONNE INTO id_personne;
            -- Si non, on vérifie si la personne est déjà un étudiant
        ELSE
            BEGIN
                -- Compte le nombre d'étudiants qui possèdent le même id de personne
                SELECT COUNT(*) INTO nombre_etudiant_avec_meme_personne FROM ETUDIANT WHERE ID_PERSONNE = id_personne;
                -- Si le nombre est supérieur à 0, on lève une exception, car l'étudiant existe déjà
                IF nombre_etudiant_avec_meme_personne > 0 THEN
                    RAISE_APPLICATION_ERROR(-20001, 'Cet étudiant existe déjà dans la base de données.');
                END IF;
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    id_etudiant := NULL;
            END;
        END IF;

        -- Création du courriel scolaire

        -- Compte le nombre d'étudiants qui possèdent le même nom et prénom
        SELECT COUNT(*)
        INTO nombre_etudiant_avec_meme_nom_prenom
        FROM ETUDIANT
                 JOIN PERSONNE ON ETUDIANT.ID_PERSONNE = PERSONNE.ID_PERSONNE
        WHERE PERSONNE.NOM = new_nom
          AND PERSONNE.PRENOM = new_prenom;

        -- Construction du courriel scolaire
        courriel_scolaire := LOWER(new_prenom) || '.' || LOWER(new_nom) || TO_CHAR(nombre_etudiant_avec_meme_nom_prenom + 1, 'FM000') || '@uqac.ca';

        -- Création du code permanent

        -- Initialisation du générateur de nombres aléatoires
        DBMS_RANDOM.INITIALIZE(TO_NUMBER(TO_CHAR(SYSDATE, 'SSSSS')));

        -- Construction du code permanent
        code_permament := LOWER(SUBSTR(new_nom, 1, 3)) || LOWER(SUBSTR(new_prenom, 1, 1)) || TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(10000000, 99999999)));

        -- Création du nouvel étudiant
        INSERT INTO ETUDIANT (ID_DEPARTEMENT, ID_PERSONNE, CODE_STATUT, CODE_PERMANENT, COURRIEL_SCOLAIRE)
        VALUES (new_id_departement, id_personne, new_status_etudiant, code_permament, courriel_scolaire);

        -- Commit les changements dans la BD
        COMMIT;
    END;
END;
/

-- b. Ajout d'une adresse supplémentaire à un étudiant ou un enseignant.
CREATE OR REPLACE PROCEDURE AJOUTER_ADRESSE_PERSONNE(
    new_id_personne IN NUMBER,
    new_titre IN VARCHAR2,
    new_adresse_civile IN VARCHAR2,
    new_ville IN VARCHAR2,
    new_code_postal IN VARCHAR2,
    new_pays IN VARCHAR2
) AS
BEGIN
    DECLARE
        new_id_adresse NUMBER;
    BEGIN

        INSERT INTO ADRESSE (TITRE, ADRESSE_CIVILE, VILLE, CODE_POSTAL, PAYS)
        VALUES (new_titre, new_adresse_civile, new_ville, new_code_postal, new_pays)
        RETURNING ID_ADRESSE INTO new_id_adresse;

        INSERT INTO ADRESSE_PERSONNE (ID_PERSONNE, ID_ADRESSE)
        VALUES (new_id_personne, new_id_adresse);

        COMMIT;
    END;
END;
/

-- Enseignant :

-- a. Ajout.
CREATE OR REPLACE PROCEDURE AJOUTER_ENSEIGNANT(
    new_nom VARCHAR2,
    new_prenom VARCHAR2,
    new_nas VARCHAR2,
    new_date_naissance VARCHAR2,
    new_courriel_personnel VARCHAR2,
    new_numero_telephone VARCHAR2,
    new_numero_ligne_direct VARCHAR2,
    new_poste_telephone VARCHAR2,
    new_id_departement NUMBER,
    new_code_local VARCHAR2,
    new_code_status_enseignant NUMBER,
    new_date_embauche DATE) AS
BEGIN
    DECLARE
        -- Déclaration des variables
        id_personne                          NUMBER        := NULL;
        id_enseignant                        NUMBER        := NULL;
        courriel_professionnel               VARCHAR2(100) := NULL;
        nombre_enseignant_avec_meme_personne NUMBER        := 0;
        nombre_ensignant_avec_meme_nom       NUMBER        := 0;
    BEGIN
        -- Vérifie si une personne existe déjà le NAS en paramètre
        BEGIN
            SELECT ID_PERSONNE INTO id_personne FROM PERSONNE WHERE NAS = new_nas;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                id_personne := NULL;
        END;
        -- Si aucune personne n'a ce NAS, on crée une nouvelle personne
        IF id_personne IS NULL THEN
            INSERT INTO PERSONNE (NOM, PRENOM, NAS, DATE_NAISSANCE, COURRIEL_PERSONNEL, NUMERO_TELEPHONE)
            VALUES (new_nom, new_prenom, new_nas, TO_DATE(new_date_naissance, 'YYYY-MM-DD'), new_courriel_personnel,
                    new_numero_telephone)
            RETURNING ID_PERSONNE INTO id_personne;
            -- Si non, on vérifie si la personne est déjà un enseignant
        ELSE
            BEGIN
                -- Compte le nombre d'étudiants qui possèdent le même id de personne
                SELECT COUNT(*)
                INTO nombre_enseignant_avec_meme_personne
                FROM ENSEIGNANT
                WHERE ID_PERSONNE = id_personne;
                -- Si le nombre est supérieur à 0, on lève une exception, car l'ensiegnant existe déjà
                IF nombre_enseignant_avec_meme_personne > 0 THEN
                    RAISE_APPLICATION_ERROR(-20001, 'Cet enseignant existe déjà dans la base de données.');
                END IF;
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    id_enseignant := NULL;
            END;
        END IF;

        -- Création du courriel professionnel

        -- Compte le nombre d'enseignant qui possèdent le même nom et prénom
        SELECT COUNT(*)
        INTO nombre_ensignant_avec_meme_nom
        FROM ENSEIGNANT
                 JOIN PERSONNE ON ENSEIGNANT.ID_PERSONNE = PERSONNE.ID_PERSONNE
        WHERE PERSONNE.NOM = new_nom
          AND PERSONNE.PRENOM = new_prenom;

        -- Construction du courriel professionnel
        courriel_professionnel :=
                LOWER(new_prenom) || '_' || LOWER(new_nom) || TO_CHAR(nombre_ensignant_avec_meme_nom + 1, 'FM00') ||
                '@uqac.ca';

        -- Création du nouvel enseignant
        INSERT INTO ENSEIGNANT (ID_DEPARTEMENT, ID_PERSONNE, CODE_LOCAL, CODE_STATUT, COURRIEL_PROFESSIONNEL,
                                NUMERO_LIGNE_DIRECT, POSTE_TELEPHONE, DATE_EMBAUCHE)
        VALUES (new_id_departement, id_personne, new_code_local, new_code_status_enseignant, courriel_professionnel,
                new_numero_ligne_direct, new_poste_telephone, new_date_embauche);

        -- Commit les changements dans la BD
        COMMIT;
    END;
END;
/

-- c. Assigner un départ d'enseignant
CREATE OR REPLACE PROCEDURE DEPART_ENSEIGNANT(
    p_id_enseignant IN NUMBER
)
IS
BEGIN
    -- Changer le statut de l'enseignant à "non-active"
    UPDATE ENSEIGNANT
    SET CODE_STATUT = 0
    WHERE ID_ENSEIGNANT = p_id_enseignant;

    COMMIT;
END;
/


CREATE OR REPLACE PROCEDURE AJOUTER_COURS_ENSEIGNE (
    p_id_enseignant IN NUMBER,
    p_id_session    IN NUMBER,
    p_id_cours      IN NUMBER,
    p_code_local    IN NCHAR
)
IS
BEGIN
    INSERT INTO COURS_ENSEIGNE (ID_ENSEIGNANT, ID_SESSION_, ID_COURS, CODE_LOCAL)
    VALUES (p_id_enseignant, p_id_session, p_id_cours, p_code_local);

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSCRIRE_ETUDIANT_COURS_ENSEIGNE (
    p_id_etudiant      IN NUMBER,
    p_id_cours_enseigne IN NUMBER,
    p_code_statut      IN VARCHAR2,
    p_note_totale      IN NUMBER
)
IS
BEGIN

    -- Insérer l'entrée dans la table ETUDIANT_COURS_ENSEIGNE
    INSERT INTO ETUDIANT_COURS_ENSEIGNE (
        ID_ETUDIANT, 
        ID_COURS_ENSEIGNE, 
        CODE_STATUT, 
        NOTE_TOTALE
    ) VALUES (
        p_id_etudiant, 
        p_id_cours_enseigne, 
        p_code_statut, 
        p_note_totale
    );
	COMMIT;
END;
/


/*===========================================================================================*/
/*======================================== Tâche 2.1 ========================================*/
/*===========================================================================================*/
/*================================== Création d'une vue =====================================*/

CREATE OR REPLACE VIEW VUE_DEPARTEMENT_DIRECTEUR AS
SELECT D.ID_DEPARTEMENT,
       D.NOM                AS NOM_DEPARTEMENT,
       D.NUMERO_DEPARTEMENT,
       P.NOM                AS NOM_DIRECTEUR,
       P.PRENOM             AS PRENOM_DIRECTEUR
FROM DEPARTEMENT D
         LEFT JOIN
     ENSEIGNANT E ON D.ID_DIRECTEUR = E.ID_ENSEIGNANT
         LEFT JOIN
     PERSONNE P ON E.ID_PERSONNE = P.ID_PERSONNE;

/*===========================================================================================*/	 
/*=============================== Tâches supplémentaires ====================================*/

-- a. Connaître la liste des cours auxquels peut s’inscrire un étudiant.
CREATE OR REPLACE VIEW VUE_COURS_DISPONIBLES AS
SELECT CE.ID_COURS_ENSEIGNE,
	   C.TITRE, 
	   C.SIGLE, 
	   CE.CODE_LOCAL, 
	   C.CREDIT, 
       C.NOMBRE_HEURE_COURS, 
	   C.NOMBRE_HEURE_LABORATOIRE, 
	   E.ID_ETUDIANT, 
	   S.ID_SESSION_
FROM COURS_ENSEIGNE CE
JOIN COURS C ON CE.ID_COURS = C.ID_COURS
JOIN ETUDIANT E ON E.ID_DEPARTEMENT = C.ID_DEPARTEMENT
JOIN SESSION_ S ON CE.ID_SESSION_ = S.ID_SESSION_;

-- b. Connaître la liste des cours suivi pour une session.
CREATE OR REPLACE VIEW VUE_COURS_INSCRITS_ETUDIANT AS
SELECT ECE.ID_ETUDIANT_COURS_ENSEIGNE,
       E.ID_ETUDIANT,
       E.ID_DEPARTEMENT,
       C.TITRE,
       C.SIGLE,
       CE.CODE_LOCAL,
       C.CREDIT,
       C.NOMBRE_HEURE_COURS,
       C.NOMBRE_HEURE_LABORATOIRE,
       S.ID_SESSION_,
       ECE.CODE_STATUT,
       ECE.NOTE_TOTALE
FROM ETUDIANT_COURS_ENSEIGNE ECE
JOIN COURS_ENSEIGNE CE ON ECE.ID_COURS_ENSEIGNE = CE.ID_COURS_ENSEIGNE
JOIN COURS C ON CE.ID_COURS = C.ID_COURS
JOIN ETUDIANT E ON ECE.ID_ETUDIANT = E.ID_ETUDIANT
JOIN SESSION_ S ON CE.ID_SESSION_ = S.ID_SESSION_;

-- c. Faire un bulletin des étudiants.
CREATE OR REPLACE VIEW VUE_BULLETIN_ETUDIANT AS
SELECT E.ID_ETUDIANT,
       E.CODE_PERMANENT,
       P.NOM,
       P.PRENOM,
       AVG(ECE.NOTE_TOTALE) AS MOYENNE_GENERALE,  -- Calcul de la moyenne pour l'étudiant
       LISTAGG(C.TITRE, ', ') WITHIN GROUP (ORDER BY C.TITRE) AS COURS,  -- Concaténation des titres de cours
       COUNT(*) AS NOMBRE_DE_COURS  -- Compte le nombre de cours inscrits
FROM ETUDIANT_COURS_ENSEIGNE ECE
         JOIN ETUDIANT E ON ECE.ID_ETUDIANT = E.ID_ETUDIANT
         JOIN PERSONNE P ON E.ID_PERSONNE = P.ID_PERSONNE
         JOIN COURS_ENSEIGNE CE ON ECE.ID_COURS_ENSEIGNE = CE.ID_COURS_ENSEIGNE
         JOIN COURS C ON CE.ID_COURS = C.ID_COURS
WHERE ECE.NOTE_TOTALE IS NOT NULL
GROUP BY E.ID_ETUDIANT, E.CODE_PERMANENT, P.NOM, P.PRENOM  -- Regroupement par étudiant
ORDER BY E.ID_ETUDIANT;

-- d. Obtenir une liste d'encienneté des enseignants
CREATE OR REPLACE VIEW VUE_ANTIENNETE_ENSEIGNANTS AS
SELECT P.NOM,
       P.PRENOM,
       E.CODE_STATUT,
       E.DATE_EMBAUCHE,
       E.COURRIEL_PROFESSIONNEL,
       ROUND(MONTHS_BETWEEN(SYSDATE, E.DATE_EMBAUCHE) / 12, 1) AS ANNEES_ANCIENNETE
FROM ENSEIGNANT E
         JOIN PERSONNE P ON E.ID_PERSONNE = P.ID_PERSONNE
WHERE E.CODE_STATUT != 0 -- Retirer les enseignants non actifs
ORDER BY E.DATE_EMBAUCHE;